config/routes.rb
Rails.application.routes.draw do

  get '/contact', to:'pages#contact'
  get '/about', to:'pages#about'
#  get '/login', to:'pages#login'


  get '/signup', to:'users#new'
  resources :users, except: [:new]

  #Simula login
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root :to => 'pages#home'

  resources :products

  resources :categories, except: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :product_categories
  has_many :categories, through: :product_categories
  validates :user_id, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
 has_many :products
 before_save { self.email = email.downcase }

 validates :username, presence: true, uniqueness: { case_sensitive: false },
 length: {minimum: 3, maximum: 25}

 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

 validates :email, presence: true, length: {maximum: 105},
           uniqueness: { case_sensitive: false },
           format: { with: VALID_EMAIL_REGEX }

 has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #Al ponerlos como helpers, estan disponibles para las vistas
  helper_method :current_user, :logged_in?

  def current_user
    #Se trae l id de session, para buscar en la db para conseguir el obj user
    #Si no existe, hace la busqueda si existe no busca
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

  end

  def logged_in?(*args)
    #true si hay un current user
    !!current_user

  end

  def required_user(*args)
    #Si no esta logeado, redirecciona el usuario
    if !logged_in?
      flash[:danger] = "Debes estar logeado para hacer esa acción"
      redirect_to root_path
   end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "La categoria fue creada con éxito"
      redirect_to categories_path

    else
      render 'new'
    end

  end

  private
  def category_params
    params.require(:category).permit(:name, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def product
  end

  def login
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # se asegura que seas un user, para usar las acciones CRUD, EDIT, UPDATE, DESTROY, CREATE
  before_action :ensure_user, only: [:edit, :update, :destroy, :create]

  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
      @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "El producto fue actualizado"
    redirect_to product_path
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "El producto fue actualizado"
    #  redirect_to product_path(@product) if logged_in?
      redirect_to product_path(@product)

    end
  end

  def create
    @product = Product.new(product_params)
    #Es para asegurar que cada producto creado tenga un usuario que es el primero de la tabla*
    @product.user = User.first
    if @product.save
      flash[:notice] = "El producto fue añadido con éxito"
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :summary, :description, :body, :image1, :image2, :image3, :image4)
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def ensure_user
      if current_user.nil?
        flash[:notice] = ("solo usuarios")
        redirect_to root_path
        return true
      else
        false
      end

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  #Login
  def create
#    debugger
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Te has logeado exitosamente"
      redirect_to products_path()
    else
      flash.now[:danger] = "Hay algo mal con tu inicio de sesion"
      render 'new'
    end

  end

  #Stop session
  def destroy
    session[:user_id] = nil
    flash[:success] = "Te has deslogeado con éxito"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new(*args)
    @user = User.new
  end

  def create(*args)
#    debugger
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Bienvenido a TiendaCNC"
      redirect_to products_path
    else
      render 'new'
    end

  end

  private
  def user_params(*args)
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<div class="container marketing">
 <div class="album text-muted">
            <div class="row">
                     <% @category.each do |category| %>
                            <div class="card">
                                <p class="card-text-title"><%= category.name %></p>
                                <%= image_tag(category.icon, size: "356x330", alt: category.name ) %>
                                <p class="card-text">
                                  <%= category.description %>
                                  <%= link_to 'Ver más', category_path(category) %>
                                </p>
                                <% if logged_in? %>
                                    <p class="card-text">
                                      <%= link_to '[ Editar ] ', edit_category_path(category) %>
                                      <%= link_to '[ Ver más ] ', category_path(category) %>
                                      <%= link_to '[ Borrar ]', category_path(category), method: :delete,data:{confirm:"¿Estas seguro?"}%>
                                    </p>
                                <% end %>
                            </div>
                     <% end %>
             </div>

             <p>
                <% if logged_in? %>
                   <%= link_to '[ Dar de alta una nueva categoria ]', new_category_path %>
                <% end %>
             </p>

      </div>


    <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

app/views/categories/new.html.erb
<div class="container">

<h1>Añadir una categoria</h1>
      <% if @category.errors.any? %>
        <h2>Los siguientes errores impiden la creación del categoryo</h2>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      <% end %>

        <%= form_for @category, :html => { role: "form"}  do |f| %>
        <p>
          <%= f.label :name, :class=>"sr-only" %> </br>
          <%= f.text_field :name, placeholder: "Nombre de la categoria", :class=>"form-control" %> </br>
        </p>

        <p>
          <%= f.label :description, :class=>"sr-only" %> </br>
          <%= f.text_area :description, placeholder: "Introduce la descripción del categoria", :class=>"form-control" %> </br>
        </p>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-8 center">
                <%= f.submit(@category.new_record? ? "Añadir Categoria" : "Actualizar Categoria", class: 'btn btn-primary btn-lg') %>
              </div>
            </div>
      <% end %>
           <hr class="featurette-divider">
           <!-- /END THE FEATURETTES -->

app/views/categories/show.html.erb
<h1>Mostrar todas las categorias</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiendaCNC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>

    <%= render 'shared/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<p></p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
<%==  %>

app/views/pages/home.html.erb
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-left">
              <h1>Example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption d-none d-md-block">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img class="third-slide" src="http://www.unique-cnc.com/assets/img/carousel/main-image-router.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-right">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="rounded-circle" src="http://www.unique-cnc.com/assets/img/carousel/main-image-router.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" src="generic.png" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 push-md-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 pull-md-7">
          <img class="featurette-image img-fluid mx-auto" src="generic.png" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" src="generic.png" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

app/views/pages/login.html.erb
<div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

app/views/pages/product.html.erb
<div class="container">
<div class="album text-muted">
              <!--ROW START -->
        <div class="row">
          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>

          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>

          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>


          <div class="card">
            <img data-src="holder.js/100px280/thumb" alt="Card image cap">
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
        <!--ROW START -->
        </div>
       <hr class="featurette-divider">

app/views/products/edit.html.erb
<div class="container">


<h1>Editando un producto existente</h1>
      <% if @product.errors.any? %>
        <h2>Los siguientes errores impiden la creación del producto</h2>
        <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      <% end %>

        <%= form_for @product, :html => { role: "form"}  do |f| %>
        <p>
          <%= f.label :name, :class=>"sr-only" %> </br>
          <%= f.text_field :name, placeholder: "Nombre del producto", :class=>"form-control" %> </br>
        </p>

        <p>
          <%= f.label :summary, :class=>"sr-only" %> </br>
          <%= f.text_area :summary, placeholder: "Resumen del producto", :class=>"form-control" %> </br>
        </p>

        <p>
          <%= f.label :description, :class=>"sr-only" %> </br>
          <%= f.text_area :description, placeholder: "Introduce la descripción del producto", :class=>"form-control" %> </br>
        </p>

        <p>
          <%= f.label :body, :class=>"sr-only" %> </br>
        <%= f.text_area(:body, placeholder: "Introduce la descripción completa del producto", :size=>"90",  :class=>"form-control") %> </br>
        </p>

        <p>
          <%= f.label :image1, :class=>"sr-only" %> </br>
        <%= f.text_field :image1, placeholder: "Nombre de la imagen 1", :class=>"form-control" %> </br>
        </p>

        <p>
          <%= f.label :image2, :class=>"sr-only" %> </br>
          <%= f.text_field :image2, placeholder: "Nombre de la imagen 2", :class=>"form-control"  %> </br>
        </p>

        <p>
          <%= f.label :image3, :class=>"sr-only" %> </br>
          <%= f.text_field :image3, placeholder: "Nombre de la imagen 3", :class=>"form-control" %> </br>
        </p>

        <p>
          <%= f.label :image4, :class=>"sr-only" %> </br>
          <%= f.text_field :image4, placeholder: "Nombre de la imagen 4", :class=>"form-control"%> </br>
        </p>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-8 center">
                <%= f.submit(@product.new_record? ? "Añadir producto" : "Actualizar producto", class: 'btn btn-primary btn-lg') %>
              </div>
            </div>
      <% end %>
           <hr class="featurette-divider">
           <!-- /END THE FEATURETTES -->

app/views/products/index.html.erb
<div class="container marketing">
 <div class="album text-muted">
            <div class="row">
                     <% @product.each do |product| %>
                            <div class="card">
                                <p class="card-text-title"><%= product.name %></p>
                                <%= image_tag(product.image1, size: "356x330", alt: product.name ) %>
                                <p class="card-text">
                                  <%= product.summary %>
                                  <%= link_to 'Ver más', product_path(product) %>
                                </p>
                                <% if logged_in? %>
                                    <p class="card-text">
                                      <%= link_to '[ Editar ] ', edit_product_path(product)%>
                                      <%= link_to '[ Ver más ] ', product_path(product) %>
                                      <%= link_to '[ Borrar ]', product_path(product), method: :delete,data:{confirm:"¿Estas seguro?"}%>
                                    </p>
                                <% end %>
                            </div>
                     <% end %>
             </div>

             <p>
                <% if logged_in? %>
                   <%= link_to '[ Dar de alta nuevo productos ]', new_product_path %>
                <% end %>
             </p>

      </div>


    <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

app/views/products/show.html.erb
<div class="container marketing" style="margin-top: 10px">

      <!-- START THE FEATURETTES -->


      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"><%= @product.name %> <span class="text-muted">Fresadora en 2 ejes</span></h2>
          <p class="lead"><%= @product.summary %></p>
          <p class="lead"></p>
          <%= sanitize @product.description, tags: %w(ul li), attributes: %w(id class style src) %>

        </div>
        <div class="col-md-5">
            <!-- Caroucel-->

       <div id="carouselProducts" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <%= image_tag(@product.image1, class: "featurette-image img-fluid mx-auto") %>
            </div>
            <div class="carousel-item">
              <%= image_tag(@product.image2, class: "d-block img-fluid") %>
            </div>
            <div class="carousel-item">
              <%= image_tag(@product.image3, class: "d-block img-fluid") %>
            </div>
            <div class="carousel-item">
              <%= image_tag(@product.image4, class: "d-block img-fluid") %>
            </div>

          </div>
          <a class="carousel-control-prev" href="#carouselProducts" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselProducts" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>


            <!-- Caroucel-->
        </div>
      </div>



      <%= sanitize @product.body, tags: %w(table tbody th tr td h3 p ul li em img button div), attributes: %w(id class style src) %>
      <hr class="featurette-divider">
      <div class="center">
       <%= link_to "Pida una cotización hoy", contact_path, class: "btn btn-lg btn-primary" %>
      </div>
</div>


<%if logged_in? %>
    <div class="center">
     <%= link_to "[ Editar este producto ]", edit_product_path(@product) %>
     <%= link_to "[ Volver al listado de productos ]", products_path %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
     <!-- FOOTER -->
      <footer>
        <p class="float-right"><a href="#">Subir</a></p>
        <p>&copy; 2017 ServoSystem, Tienda CNC la tienda online de partes para CNC. &middot; <a href="/contact">Contacto</a> &middot; </p>
      </footer>

    </div><!-- /.container -->

app/views/shared/_nav.html.erb
<!-- NAV START-->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <!--
     <a class="navbar-brand" href="#">ServoSystem</a>
     -->
    <%= link_to "ServoSystem", root_path, id: "logo", class: "navbar-brand"%>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if (current_page?(controller:'pages', action:'home')) %> <li class="nav-item active"> <% else %> <li class="nav-item"><% end %>
     <!--
     <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
       -->
      <%= link_to "Inicio", root_path, class: 'nav-link' %>
      </li>

      <% if (current_page?(controller:'products', action:'index')) %> <li class="nav-item dropdown"> <% else %> <li class="nav-item dropdown"><% end %>
          <!--      <li class="nav-item dropdown"> -->
          <a class="nav-link dropdown-toggle" href="/products" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Productos</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">CNC</a>
          <a class="dropdown-item" href="#">PLC con arduino</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Automatización</a>
        </div>
      </li>

      <% if (current_page?(controller:'pages', action:'contact')) %> <li class="nav-item active"> <% else %> <li class="nav-item"><% end %>
      <!--
      <a class="nav-link" href="#">Products</a>
        -->
      <%= link_to "Contacto", contact_path, class: 'nav-link' %>
      </li>

      <% if logged_in? %>
      <li>
        <%= link_to 'Logout', logout_path, class: 'nav-link', method: :delete %>
      </li>
      <% else %>
      <li>
        <%= link_to 'Inicia sesión', login_path, class: 'nav-link' %>
      </li>
      <% end %>

      <% if logged_in? %>
      <li>
        <p> ESTAS LOGEADO :)</p>
      </li>
      <% else %>
      <li>
        <p> NO LOGEADO :)</p>
      </li>
      <% end %>



    </ul>
    <form class="form-inline my-2 my-lg-0">
      <!--
      <input class="form-control mr-sm-2" type="search" placeholder="Todo a un clic de distancia" aria-label="Buscar">
      <button class="btn btn-outline-success my-2 my-sm-0 search-btn" type="submit">Buscar</button>
        -->
    </form>
  </div>
</nav>
<!-- NAV END -->